#!/usr/bin/env python2
import sys, os, time, subprocess
from pdb import set_trace


configs = {}
inf = open('ttbarxsec.cfg')
data = inf.read()
data = data.split('\n')
for l in data:
	l = l.split('#')[0]
	if '=' in l:
		name = l.split('=')[0].strip()
		val = l.split('=')[1].strip()
		configs[name] = val

print configs

swdir = os.path.realpath(os.environ['URA_PROJECT'])
jobid = os.environ['jobid']
inputdir = os.path.join(swdir, 'inputs')
inputdir = os.path.join(inputdir, jobid)

jobdir = sys.argv[1]
exe = sys.argv[2]
execonfig = sys.argv[3]
jobargs = sys.argv[4:]

#os.system('git commit -a -m ' + jobdir)

#os.mkdir('Production_'+ time.strftime("%Y-%m-%d_%H:%M:%S", time.gmtime()))
if os.path.isdir(jobdir):
	print jobdir, 'exists: EXIT'
	sys.exit(-1)
jobdir = os.path.join(os.getcwd(), jobdir)
os.mkdir(jobdir)

os.system('cp ' + execonfig + ' ' + jobdir)
execonfig = os.path.join(jobdir, os.path.basename(execonfig))

p = subprocess.Popen(['which', exe], stdout=subprocess.PIPE)
exe = p.stdout.read().split('\n')[0]
cpcomm = 'cp ' + exe + ' ' + jobdir
os.system(cpcomm)
exe = os.path.join(jobdir, os.path.basename(exe))
#print exe, execonfig

files = os.listdir(inputdir)

samplefiles = [f for f in files if 'txt' in f]

transferdir = os.path.join(inputdir, 'INPUT')
transferfiles = []
if os.path.isdir(transferdir):
	transferfiles = os.listdir(transferdir)

transferfiles = [os.path.join(transferdir, tf) for tf in transferfiles]
transferfiles.append(execonfig)

transferfiles_config = ', '.join(transferfiles)

for sf in samplefiles:
	if 'QCD' in sf or 'DYJet' in sf or 'WJet' in sf:
		filesperjob = 60
	elif 'DATA' in sf:
		filesperjob = 80
	elif 'Hpp' in sf:
		filesperjob = 20
	elif 'tt_' in sf:
		if configs['PDFTEST'] == '1' and 'tt_PowhegP8' in sf:
			filesperjob = 10
		else:
			filesperjob = 60
	else:
		filesperjob = 60

	#infile = os.path.join(inputdir, sf)
	jobpath = os.path.join(jobdir, sf.split('.txt')[0])
	os.mkdir(jobpath)
	infile = os.path.join(jobpath, sf)
	print 'cp ' + os.path.join(inputdir, sf) + ' ' + infile
	os.system('cp ' + os.path.join(inputdir, sf) + ' ' + infile)
	infiledes = open(infile, 'r')
	numrootfiles = infiledes.read().count('.root')
	infiledes.close()
	numjobs = max(numrootfiles/filesperjob, 1)
	sample = sf.split('.txt')[0]
	print sf, numjobs
	for j in range(0, numjobs):
		condorfile ="""universe = vanilla
Executable = batch_job.sh
Should_Transfer_Files = YES
WhenToTransferOutput = ON_EXIT
Transfer_Input_Files = {5}
Output = con_{2}.stdout
Error = con_{2}.stderr
Arguments = {0} {1} {6}_out_{2}.root --thread 1 --j {2} --J {3} {4}
Queue

		""".format(exe, infile, j, numjobs, ' '.join(jobargs), transferfiles_config, sample)
        
		conf = open(os.path.join(jobpath, 'condor_'+str(j)+'.jdl'), 'w')
		conf.write(condorfile)
		conf.close()

	batch_job="""#!/bin/bash
WORKINGDIR=$PWD
echo $HOSTNAME
echo $WORKINGDIR
ls -lht {0}
cd {0}
source environment.sh
cd $WORKINGDIR

PA=$@
PA=${{PA#* }}

EXE=$1

pwd
ls -lht

echo $EXE
echo $PA

$EXE $PA 

	""".format(swdir)

	conf = open(os.path.join(jobpath, 'batch_job.sh'), 'w')
	conf.write(batch_job)
	conf.close()
        
	for j in range(0, numjobs):
		os.system('cd ' + jobpath + ' && condor_submit condor_'+str(j)+'.jdl')

